# Generated by Django 5.1.3 on 2024-11-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_profile_picture_remove_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('office_staff', 'Office Staff'), ('driver', 'Driver')], default='customer', max_length=20),
        ),
    ]
