# Generated by Django 4.2.17 on 2024-12-12 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='container',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='customer',
        ),
        migrations.AddField(
            model_name='container',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.driver'),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
