# Generated by Django 5.1.1 on 2024-11-28 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_driver_license_number_alter_booking_booking_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
    ]
