# Generated by Django 5.1.3 on 2024-11-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
